name: Build and Push Docker image

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            chiefsphinx/joecow.in:latest
            chiefsphinx/joecow.in:${{ steps.vars.outputs.SHORT_SHA }}
          build-args: |
            VITE_POSTHOG_KEY=${{ secrets.VITE_POSTHOG_KEY }}
            VITE_POSTHOG_HOST=${{ secrets.VITE_POSTHOG_HOST }}

  deploy-to-appservice:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-joecowin-prod'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'chiefsphinx/joecow.in:${{ needs.build-and-push.outputs.SHORT_SHA }}'